### ISSUE TITLE
post-merge hook

### ISSUE THREAD

**Issue by Faryshta** [bruli/php-git-hooks#58]
Hi, it would be nice to have a post-merge hook to deal things like

- execute composer update if the file `composer.json` was edited.
- execute phpunit if any of the tests got updated.

That way I won't have to send an email to my team everytime I edit the composer asking them to execute the composer update command

**Comment by bruli** [comment]
Hi.

I'm working on a pre-push hook to execute unit tests, but the status is WIP.
I don't like post-merge hook because you can merge a branch in your server instead your local environment. The goal for this tool is checking your code in your local environment before share it with all the team. 
Off course, any suggestion is wellcome.

**Comment by Faryshta** [comment]
a way to solve the server problem would be something like what yii2 have.

we include a file php-git-hooks.local.yml which will be on the .gitignore list.

That mean such file won't be commited and will be able to handle configurations specifics for each device.

For exaple de activate `post-merge` on production server.
